# Generated by Django 6.0 on 2025-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeathRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('death_rate_air_pollution', models.FloatField(blank=True, null=True)),
                ('death_rate_household_solid_fuels', models.FloatField(blank=True, null=True)),
                ('death_rate_ambient_pm', models.FloatField(blank=True, null=True)),
                ('death_rate_ambient_ozone', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country_code', 'year'], name='api_deathra_country_b4921e_idx'), models.Index(fields=['year'], name='api_deathra_year_916e04_idx')],
                'unique_together': {('country_code', 'year')},
            },
        ),
    ]
